sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t masonyen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true masonyen/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-633215246111"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


